<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'site.name',
                'value' => 'Campus Rating System',
                'type' => 'string',
                'group' => 'general',
                'subgroup' => 'site',
                'label' => 'Site Name',
                'description' => 'Nama website',
                'sort_order' => 1,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => true,
            ],
            [
                'key' => 'site.description',
                'value' => 'Platform evaluasi fasilitas kampus',
                'type' => 'string',
                'group' => 'general',
                'subgroup' => 'site',
                'label' => 'Site Description',
                'description' => 'Deskripsi website',
                'sort_order' => 2,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => true,
            ],
            [
                'key' => 'site.logo',
                'value' => '/images/logo.png',
                'type' => 'string',
                'group' => 'general',
                'subgroup' => 'site',
                'label' => 'Logo',
                'description' => 'Path logo website',
                'sort_order' => 3,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => true,
            ],

            // Rating Settings
            [
                'key' => 'rating.min_score',
                'value' => '1',
                'type' => 'integer',
                'group' => 'rating',
                'subgroup' => 'scoring',
                'label' => 'Minimum Score',
                'description' => 'Nilai minimum rating',
                'sort_order' => 1,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => false,
            ],
            [
                'key' => 'rating.max_score',
                'value' => '5',
                'type' => 'integer',
                'group' => 'rating',
                'subgroup' => 'scoring',
                'label' => 'Maximum Score',
                'description' => 'Nilai maksimum rating',
                'sort_order' => 2,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => false,
            ],
            [
                'key' => 'rating.allow_editing',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'rating',
                'subgroup' => 'behavior',
                'label' => 'Allow Editing',
                'description' => 'Izinkan mahasiswa mengedit rating',
                'sort_order' => 3,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => false,
            ],

            // Report Settings
            [
                'key' => 'report.auto_assign',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'report',
                'subgroup' => 'handling',
                'label' => 'Auto Assign',
                'description' => 'Otomatis assign laporan ke admin',
                'sort_order' => 1,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => false,
            ],
            [
                'key' => 'report.notification_email',
                'value' => 'admin@campus.com',
                'type' => 'string',
                'group' => 'report',
                'subgroup' => 'notification',
                'label' => 'Notification Email',
                'description' => 'Email untuk notifikasi laporan baru',
                'sort_order' => 2,
                'is_editable' => true,
                'is_visible' => true,
                'is_public' => false,
            ],

            // Email Settings
            [
                'key' => 'mail.driver',
                'value' => 'smtp',
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'server',
                'label' => 'Mail Driver',
                'description' => 'Driver pengiriman email',
                'options' => json_encode(['smtp', 'sendmail', 'mailgun']),
                'sort_order' => 1,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.host',
                'value' => 'smtp.mailtrap.io',
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'server',
                'label' => 'Mail Host',
                'sort_order' => 2,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.port',
                'value' => '2525',
                'type' => 'integer',
                'group' => 'mail',
                'subgroup' => 'server',
                'label' => 'Mail Port',
                'sort_order' => 3,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.username',
                'value' => null,
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'authentication',
                'label' => 'Mail Username',
                'sort_order' => 4,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.password',
                'value' => null,
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'authentication',
                'label' => 'Mail Password',
                'sort_order' => 5,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.encryption',
                'value' => 'tls',
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'server',
                'label' => 'Mail Encryption',
                'options' => json_encode(['tls', 'ssl', null]),
                'sort_order' => 6,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.from_address',
                'value' => 'noreply@campus.com',
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'sender',
                'label' => 'From Address',
                'sort_order' => 7,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
            [
                'key' => 'mail.from_name',
                'value' => 'Campus Rating',
                'type' => 'string',
                'group' => 'mail',
                'subgroup' => 'sender',
                'label' => 'From Name',
                'sort_order' => 8,
                'is_editable' => true,
                'is_visible' => false,
                'is_public' => false,
                'required_permission' => 'super_admin',
            ],
        ];

        foreach ($settings as $setting) {
            Setting::create($setting);
        }
    }
}